import type { CardProps } from '../components/card/Card'

export const cards: CardProps[] = [
  {
    name: 'Alien Axe',
    image: 'alien-axe.png',
    cooldown: 10,
    effect: '11 Damage',
    passive: 'When you get this, gain 2 speed permanently.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Bluenanas',
    image: 'bluenanas.png',
    cooldown: 10,
    effect: '15 health',
    passive: 'When you get this, +10 Max Health.',
    cost: 1,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Candy Mail',
    image: 'candy-mail.png',
    cooldown: 25,
    effect: '100 Shield',
    passive:
      'When you take damage, 3 Joy. If you use this 4 more times gain 60 Armor permanently and destroy this item.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Clockwork Blades',
    image: 'clockwork-blades.png',
    cooldown: 14,
    effect: '16 Damage',
    passive: 'Adjacent items charge 20% faster.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Colossal Popsicle',
    image: 'colossal-popsicle.png',
    cooldown: 11,
    effect: '15 Damage\n2 Seconds Freeze on three items.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Epicurean Chocolate',
    image: 'epicurean-chocolate.png',
    cooldown: 30,
    effect: '100 Health',
    passive:
      'When you take damage, 3 Joy. If you use this 4 more times, gain 75 Max Health permanently and destroy this item.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Ectoplasm',
    image: 'ectoplasm.png',
    cooldown: 5,
    effect: 'Heal 5 Health\nRemove 10 Burn and 3 Poison.',
    passive: '',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Electric Eels',
    image: 'electric-eels.png',
    cooldown: 7,
    effect: '18 Damage',
    passive: 'When you take damage from a weapon, 2 second daze.',
    cost: 0,
    types: ['Aquatic', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Exoskeleton',
    image: 'exoskeleton.png',
    cooldown: 0,
    effect: '',
    passive: 'Adjacent weapons get +6 damage',
    cost: 1,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Fang',
    image: 'fang.png',
    cooldown: 4,
    effect: 'Deal 1 Damage',
    passive: '',
    cost: 0,
    types: ['Weapon', ' Monstrous'],
    size: 'small',
  },
  {
    name: 'Hakurvan Launcher',
    image: 'hakurvan-launcher.png',
    cooldown: 24,
    effect: '50 Damage',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Hot Springs',
    image: 'hot-springs.png',
    cooldown: 16,
    effect: 'Heal 40 Health',
    passive: '',
    cost: 1,
    types: ['Building'],
    size: 'large',
  },
  {
    name: 'Improvised Bludgeon',
    image: 'improvised-bludgeon.png',
    cooldown: 5,
    effect: '10 Damage\n5 Daze',
    passive: 'When used, increase the cooldown by 4 seconds.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Junkyard Lance',
    image: 'junkyard-lance.png',
    cooldown: 14,
    effect: '20 Damage + 5 Damage per small weapon you own.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Kirg Salamander Pup',
    image: 'kirg-salamander-pup.png',
    cooldown: 13,
    effect: '5 Burn',
    passive: 'When you buy this, gain 20 Max Health.',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: 'Knee Brace',
    image: 'knee-brace.png',
    cooldown: 5,
    effect: '5 Health',
    passive: 'When you buy this, gain 5 armor.',
    cost: 0,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Lifting Gloves',
    image: 'lifting-gloves.png',
    cooldown: 9,
    effect: '1 Strength',
    passive: 'When you buy this gain 1 Strength permanently.',
    cost: 1,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Makeshift Barricade',
    image: 'makeshift-barricade.png',
    cooldown: 10,
    effect: '10 Shield',
    passive: 'When you buy this gain 10 Armor.',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: 'Magma core',
    image: 'magma-core.png',
    cooldown: 4,
    effect: 'Burn 4',
    passive:
      'Each time this item is used , increase CD by 4 sec for this fight',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Magnifying Glass',
    image: 'magnifying-glass.png',
    cooldown: 11,
    effect: '11 Damage',
    passive: '',
    cost: 1,
    types: ['Tools', ' Weapon'],
    size: 'small',
  },
  {
    name: 'Marble Scale Mail',
    image: 'marble-scale-mail.png',
    cooldown: 0,
    effect: '',
    passive: '30 Armor',
    cost: 1,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Medi-Calixto',
    image: 'medi-calixto.png',
    cooldown: 9,
    effect: '7 Health for each medium item you own.',
    passive: '',
    cost: 1,
    types: ['Friend'],
    size: 'medium',
  },
  {
    name: 'Old Sword',
    image: 'old-sword.png',
    cooldown: 6,
    effect: 'Deal 3 Damage',
    passive: '',
    cost: 0,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Power Shoes',
    image: 'power-shoes.png',
    cooldown: 10,
    effect: '6 Speed',
    passive: 'When you gain this, +2 Speed permanently.',
    cost: 1,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Rocket Boots',
    image: 'rocket-boots.png',
    cooldown: 0,
    effect: '20 Speed',
    passive: '',
    cost: 1,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Scythe',
    image: 'scythe.png',
    cooldown: 10,
    effect: '',
    passive: 'Deals damage equal to 40% of opponents health.',
    cost: 0,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Spiked Buckler',
    image: 'spiked-buckler.png',
    cooldown: 9,
    effect: '6 Damage\n6 Shield',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Super Syrup',
    image: 'super-syrup.png',
    cooldown: 25,
    effect: 'Adavance all other items by 3 Seconds.',
    passive:
      'When you take damage, 3 Joy. If you use this 4 more times gain 10 Speed permanently and destroy this item.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Temporary Shelter',
    image: 'temporary-shelter.png',
    cooldown: 0,
    effect: 'You have +50 max health while you own this.',
    passive: '',
    cost: 0,
    types: [],
    size: 'large',
  },
  {
    name: 'Titans Blade',
    image: 'titans-blade.png',
    cooldown: 16,
    effect: '50 Damage',
    passive:
      'If you have 20 Strength, this items cooldown is halved. If you have 500 Max Health, this item has dualcast.',
    cost: 6,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Tourist Chariot',
    image: 'tourist-chariot.png',
    cooldown: 12,
    effect: '30 Shield',
    passive: '',
    cost: 1,
    types: ['Vehicle'],
    size: 'large',
  },
  {
    name: 'Trained Spider',
    image: 'trained-spider.png',
    cooldown: 11,
    effect: '1 Poison',
    passive: '',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Whip',
    image: 'whip.png',
    cooldown: 9,
    effect: '6 Damage',
    passive: 'When you use an adjacent item, deal 2 damage.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
]
