import type { CardProps } from '../components/card/Card'

export const neutralCards: CardProps[] = [
  {
    name: 'Alien Axe',
    image: 'alien-axe.png',
    cooldown: 10,
    effect: '11 Damage',
    passive: 'When you get this, gain 2 speed permanently.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Bluenanas',
    image: 'bluenanas.png',
    cooldown: 10,
    effect: '15 health',
    passive: 'When you get this, +10 Max Health.',
    cost: 1,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Candy Mail',
    image: 'candy-mail.png',
    cooldown: 25,
    effect: '100 Shield',
    passive:
      'When you take damage, 3 Joy. If you use this 4 more times gain 60 Armor permanently and destroy this item.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Clockwork Blades',
    image: 'clockwork-blades.png',
    cooldown: 14,
    effect: '16 Damage',
    passive: 'Adjacent items charge 20% faster.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Colossal Popsicle',
    image: 'colossal-popsicle.png',
    cooldown: 11,
    effect: '15 Damage\n2 Seconds Freeze on three items.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Epicurean Chocolate',
    image: 'epicurean-chocolate.png',
    cooldown: 30,
    effect: '100 Health',
    passive:
      'When you take damage, 3 Joy. If you use this 4 more times, gain 75 Max Health permanently and destroy this item.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Ectoplasm',
    cooldown: 5,
    effect: 'Heal 5 Health\nRemove 10 Burn and 3 Poison.',
    passive: '',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Electric Eels',
    image: 'electric-eels.png',
    cooldown: 7,
    effect: '18 Damage',
    passive: 'When you take damage from a weapon, 2 second daze.',
    cost: 0,
    types: ['Aquatic', 'Weapon'],
    size: 'medium',
  },
  {
    name: 'Exoskeleton',
    image: 'exoskeleton.png',
    cooldown: 0,
    effect: '',
    passive: 'Adjacent weapons get +6 damage',
    cost: 1,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Fang',
    image: 'fang.png',
    cooldown: 4,
    effect: 'Deal 1 Damage',
    passive: '',
    cost: 0,
    types: ['Weapon', 'Monstrous'],
    size: 'small',
  },
  {
    name: 'Hakurvan Launcher',
    image: 'hakurvan-launcher.png',
    cooldown: 24,
    effect: '50 Damage',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Hot Springs',
    image: 'hot-springs.png',
    cooldown: 16,
    effect: 'Heal 40 Health',
    passive: '',
    cost: 1,
    types: ['Building'],
    size: 'large',
  },
  {
    name: 'Improvised Bludgeon',
    image: 'improvised-bludgeon.png',
    cooldown: 5,
    effect: '10 Damage\n5 Daze',
    passive: 'When used, increase the cooldown by 4 seconds.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Junkyard Lance',
    image: 'junkyard-lance.png',
    cooldown: 14,
    effect: '20 Damage + 5 Damage per small weapon you own.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Kirg Salamander Pup',
    image: 'kirg-salamander-pup.png',
    cooldown: 13,
    effect: '5 Burn',
    passive: 'When you buy this, gain 20 Max Health.',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: 'Knee Brace',
    image: 'knee-brace.png',
    cooldown: 5,
    effect: '5 Health',
    passive: 'When you buy this, gain 5 armor.',
    cost: 0,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Lifting Gloves',
    image: 'lifting-gloves.png',
    cooldown: 9,
    effect: '1 Strength',
    passive: 'When you buy this gain 1 Strength permanently.',
    cost: 1,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Makeshift Barricade',
    image: 'makeshift-barricade.png',
    cooldown: 10,
    effect: '10 Shield',
    passive: 'When you buy this gain 10 Armor.',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: 'Magma core',
    image: 'magma-core.png',
    cooldown: 4,
    effect: 'Burn 4',
    passive:
      'Each time this item is used , increase CD by 4 sec for this fight',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Magnifying Glass',
    image: 'magnifying-glass.png',
    cooldown: 11,
    effect: '11 Damage',
    passive: '',
    cost: 1,
    types: ['Tools', ' Weapon'],
    size: 'small',
  },
  {
    name: 'Marble Scale Mail',
    image: 'marble-scale-mail.png',
    cooldown: 0,
    effect: '',
    passive: '30 Armor',
    cost: 1,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Medi-Calixto',
    image: 'medi-calixto.png',
    cooldown: 9,
    effect: '7 Health for each medium item you own.',
    passive: '',
    cost: 1,
    types: ['Friend'],
    size: 'medium',
  },
  {
    name: 'Old Sword',
    image: 'old-sword.png',
    cooldown: 6,
    effect: 'Deal 3 Damage',
    passive: '',
    cost: 0,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Power Shoes',
    image: 'power-shoes.png',
    cooldown: 10,
    effect: '6 Speed',
    passive: 'When you gain this, +2 Speed permanently.',
    cost: 1,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Rocket Boots',
    image: 'rocket-boots.png',
    cooldown: 0,
    effect: '20 Speed',
    passive: '',
    cost: 1,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Scythe',
    image: 'scythe.png',
    cooldown: 10,
    effect: '',
    passive: 'Deals damage equal to 40% of opponents health.',
    cost: 0,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Spiked Buckler',
    image: 'spiked-buckler.png',
    cooldown: 9,
    effect: '6 Damage\n6 Shield',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Super Syrup',
    image: 'super-syrup.png',
    cooldown: 25,
    effect: 'Adavance all other items by 3 Seconds.',
    passive:
      'When you take damage, 3 Joy. If you use this 4 more times gain 10 Speed permanently and destroy this item.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Temporary Shelter',
    cooldown: 0,
    effect: 'You have +50 max health while you own this.',
    passive: '',
    cost: 0,
    types: [],
    size: 'large',
  },
  {
    name: 'Titans Blade',
    image: 'titans-blade.png',
    cooldown: 16,
    effect: '50 Damage',
    passive:
      'If you have 20 Strength, this items cooldown is halved. If you have 500 Max Health, this item has dualcast.',
    cost: 6,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Tourist Chariot',
    image: 'tourist-chariot.png',
    cooldown: 12,
    effect: '30 Shield',
    passive: '',
    cost: 1,
    types: ['Vehicle'],
    size: 'large',
  },
  {
    name: 'Trained Spider',
    image: 'trained-spider.png',
    cooldown: 11,
    effect: '1 Poison',
    passive: '',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Whip',
    image: 'whip.png',
    cooldown: 9,
    effect: '6 Damage',
    passive: 'When you use an adjacent item, deal 2 damage.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
]

export const pygmalienCards: CardProps[] = [
  {
    name: 'Abacus',
    image: 'abacus.png',
    cooldown: 0,
    effect: '',
    passive: 'The left non-weapon item charges 25% faster.',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Atlas Stone',
    image: 'atlas-stone.png',
    cooldown: 10,
    effect: "1 Damage\nDouble this item's Damage.",
    passive: '',
    cost: 10,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Atlatl',
    image: 'atlatl.png',
    cooldown: 15,
    effect: '15 Damage',
    passive: 'Charges 10% faster for each Strength you have.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Bandages',
    image: 'bandages.png',
    cooldown: 8,
    effect: '5 Health',
    passive: 'This item heals for 3x while you are below half health.',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Belt',
    image: 'belt.png',
    cooldown: 6,
    effect: '5 Shield',
    passive: 'When you buy this, get a random item.',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: 'Billboard',
    image: 'billboard.png',
    cooldown: 7,
    effect: 'Advance adjacent items 2 Seconds.',
    passive: 'Whenever you sell an item, get 1 Strength permanently.',
    cost: 8,
    types: [],
    size: 'large',
  },
  {
    name: 'Bitey Bactrian',
    image: 'bitey-bactrian.png',
    cooldown: 10,
    effect: '20 Damage per non-weapon item you own.',
    passive: '50% Lifesteal\nDualcast while you have >50% HP.',
    cost: 12,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Boomerang',
    image: 'boomerang.png',
    cooldown: 13,
    effect: '22 Damage',
    passive: 'Whenever you Heal, advance this 2 Seconds.',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Bootstraps',
    image: 'bootstraps.png',
    cooldown: 0,
    effect: '',
    passive:
      'When you buy this gain 20 Armor. Your shielding items give for 8 extra Shield.',
    cost: 5,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Brass Knuckles',
    image: 'brass-knuckles.png',
    cooldown: 8,
    effect: '5 Damage',
    passive: 'This item gets triple bonus from Strength.',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Briefcase',
    image: 'briefcase.png',
    cooldown: 8,
    effect: 'Damage equal to 5x your Income.',
    passive: '',
    cost: 3,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Bushel',
    image: 'bushel.png',
    cooldown: 12,
    effect: 'Gain 1 Regeneration this fight.',
    passive: 'At the start of the fight get 1 Regeneration.',
    cost: 3,
    types: [],
    size: 'medium',
  },
  {
    name: 'Business Card',
    image: 'business-card.png',
    cooldown: 0,
    effect: '',
    passive: 'When you sell this, get a random small item.',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Caltrops',
    image: 'caltrops.png',
    cooldown: 0,
    effect: '',
    passive: 'Deal 3 Damage whenever you get hit.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Cargo Shorts',
    image: 'placeholder.png',
    cooldown: 7,
    effect: 'Gain 1 Strength for each small item you own.',
    passive: 'When you gain a small item, gain +5 Armor.',
    cost: 5,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Cash Cannon',
    image: 'cash-cannon.png',
    cooldown: 6,
    effect: 'Deal Damage equal to 7x your money.',
    passive: '',
    cost: 3,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Chocolate Bar',
    image: 'chocolate-bar.png',
    cooldown: 0,
    effect: '',
    passive: 'When you sell this, gain +10 Max Health.',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Crook',
    image: 'crook.png',
    cooldown: 10,
    effect: '9 Damage',
    passive: 'You have 9 Strength.',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Crystal Bonsai',
    image: 'placeholder.png',
    cooldown: 6,
    effect: 'Heal Health equal to this items value.',
    passive:
      "At the start of the fight, increase this item's value by 1. When you lose a life, destroy this.",
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Dragon Egg',
    image: 'dragon-egg.png',
    cooldown: 0,
    effect: '',
    passive:
      'When you buy this gain 20 Armor and 5 Strength, then Fight the Dragon.',
    cost: 10,
    types: [],
    size: 'small',
  },
  {
    name: 'Exotic Bird',
    image: 'placeholder.png',
    cooldown: 8,
    effect: 'Deal 13 Damage',
    passive: 'When you buy this, gain 5 Speed.',
    cost: 8,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Fixer Upper',
    image: 'fixer-upper.png',
    cooldown: 0,
    effect: '',
    passive:
      'At the start of the fight, permanently transform this into a random large item.',
    cost: 1,
    types: [],
    size: 'large',
  },
  {
    name: 'Flail',
    image: 'flail.png',
    cooldown: 8,
    effect: 'Deal 7 damage three times.',
    passive: '',
    cost: 10,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Ganjo',
    image: 'ganjo.png',
    cooldown: 9,
    effect: 'Advance all items 1 Second.',
    passive: 'At the start of the fight, gain 1 Gold.',
    cost: 3,
    types: [],
    size: 'medium',
  },
  {
    name: 'Gavel',
    image: 'gavel.png',
    cooldown: 10,
    effect: 'Deal 3 Damage',
    passive: 'When you gain Shield, give this 3 Damage for the fight.',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Grindstone',
    image: 'grindstone.png',
    cooldown: 6,
    effect:
      'Give your left weapon extra Damage equal to your Strength this fight.',
    passive: '',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Gumball Machine',
    image: 'gumball-machine.png',
    cooldown: 8,
    effect: 'Heal 12 Health',
    passive: 'You have +1 Income.',
    cost: 3,
    types: [],
    size: 'medium',
  },
  {
    name: 'Haladie',
    image: 'haladie.png',
    cooldown: 10,
    effect: 'Deal 3 Damage',
    passive: 'Dualcast',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Hatchet',
    image: 'hatchet.png',
    cooldown: 5,
    effect: 'Deal X Damage',
    passive: 'When you get this, it gains Damage equal to your gold.',
    cost: 0,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Hogwash',
    image: 'hogwash.png',
    cooldown: 11,
    effect: 'Heal 12 Health',
    passive: 'Whenever you use another item, advance this 2 seconds.',
    cost: 2,
    types: [],
    size: 'large',
  },
  {
    name: 'Ice Cream Truck',
    image: 'ice-cream-truck.png',
    cooldown: 10,
    effect: '2 Seconds Freeze on two items.',
    passive: 'When any item is frozen, heal Health equal to that items Value.',
    cost: 6,
    types: ['Vehicle'],
    size: 'large',
  },
  {
    name: 'Igloo',
    image: 'igloo.png',
    cooldown: 4,
    effect: 'Freeze a random item for 4 seconds',
    passive: '',
    cost: 3,
    types: [],
    size: 'large',
  },
  {
    name: 'Jaballian Dagger',
    image: 'jaballian-dagger.png',
    cooldown: 7,
    effect: '10 Damage',
    passive: 'If you have 10+ gold, this Weapon gets +30 Damage.',
    cost: 2,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Jaballian Drum',
    image: 'placeholder.png',
    cooldown: 10,
    effect: 'Gain Speed equal to your Strength.',
    passive: 'You have 2 Strength.',
    cost: 12,
    types: [],
    size: 'large',
  },
  {
    name: 'Jaballian Longbow',
    image: 'jaballian-longbow.png',
    cooldown: 12,
    effect: 'Deal 20 Damage',
    passive:
      'This deals double Damage if you have more current Health than you opponent.',
    cost: 3,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Jewelry',
    image: 'jewelry.png',
    cooldown: 0,
    effect: '',
    passive:
      'When you gain Shield, give your shielding items +1 for the fight.',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Kukri',
    image: 'kukri.png',
    cooldown: 7,
    effect: '7 Damage',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Landscraper',
    image: 'landscraper.png',
    cooldown: 8,
    effect: 'Gain 8 Shield and give all your shielding items +1 for the fight.',
    passive: '',
    cost: 6,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Lemonade Stand',
    image: 'lemonade-stand.png',
    cooldown: 0,
    effect: 'Heal 25 Health',
    passive: 'Whenever you sell another item, permanently gain 10 Max Health.',
    cost: 6,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Lion Cane',
    image: 'lion-cane.png',
    cooldown: 15,
    effect: 'Deal Damage equal to 20% of your current Health.',
    passive: '',
    cost: 0,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Loupe',
    image: 'loupe.png',
    cooldown: 7,
    effect: 'Give items to the left +3 Shielding.',
    passive: 'Items to the right charge 6% faster.',
    cost: 4,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Luxury Tents',
    image: 'luxury-tents.png',
    cooldown: 10,
    effect: 'Heal 20% of your Max Health',
    passive: '',
    cost: 12,
    types: [],
    size: 'large',
  },
  {
    name: 'Marbles',
    image: 'marbles.png',
    cooldown: 9,
    effect: '1 Shield',
    passive: 'When you use an item, give this +1 Shield for the fight.',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Masterpiece',
    image: 'masterpiece.png',
    cooldown: 0,
    effect: '',
    passive: 'At the start of the fight increase value by 5$',
    cost: 10,
    types: [],
    size: 'small',
  },
  {
    name: 'Matchbox',
    image: 'matchbox.png',
    cooldown: 0,
    effect: '',
    passive: 'Whenever you use a non-weapon item, Burn 3.',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Model Ship',
    image: 'model-ship.png',
    cooldown: 0,
    effect: '',
    passive: 'When you use an item, gain 3 Shield.',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Monocle',
    image: 'monocle.png',
    cooldown: 0,
    effect: '',
    passive: 'Your small items have +6 Damage.',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Oinkment',
    image: 'oinkment.png',
    cooldown: 8,
    effect: 'Heal 10 Health',
    passive:
      'When you buy this, Heal 50 Health. When you upgrade this, Heal 100 Health.',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Open/Closed Sign',
    image: 'placeholder.png',
    cooldown: 0,
    effect: '',
    passive: 'Your cooldowns are reduced by 35% until you use a weapon',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Pawn Shop',
    image: 'pawn-shop.png',
    cooldown: 0,
    effect: '',
    passive: "Your items sell for double it's value.",
    cost: 2,
    types: [],
    size: 'large',
  },
  {
    name: 'Peace Pipe',
    image: 'peace-pipe.png',
    cooldown: 10,
    effect: 'Heal 15 Health',
    passive: '',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Phonograph',
    image: 'phonograph.png',
    cooldown: 10,
    effect: 'Advance the right item 4 Seconds.',
    passive: '',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Piggy Bank',
    image: 'piggy-bank.png',
    cooldown: 0,
    effect: '4 Shield',
    passive: "At the start of the fight, increase this item's value by 2.",
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Pinata',
    image: 'pinata.png',
    cooldown: 0,
    effect: '',
    passive: 'When you sell this item, fill your board with chocolate bars',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Pocketwatch',
    image: 'pocketwatch.png',
    cooldown: 0,
    effect: '',
    passive: 'Adjacent Properties charge 30% faster.',
    cost: 8,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Pointy Tusk Armor',
    image: 'placeholder.png',
    cooldown: 14,
    effect: 'Deal 15 Damage',
    passive:
      'When you buy this, gain 10 Armor. This item gets triple bonus from Strength.',
    cost: 4,
    types: ['Weapon', ' Gear'],
    size: 'small',
  },
  {
    name: "Pyg's Gym",
    image: "pyg's-gym.png",
    cooldown: 9,
    effect: 'Gain 2 Strength and Heal 15 Health.',
    passive: 'When you buy this get 1 Strength.',
    cost: 4,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Rare Coin',
    image: 'placeholder.png',
    cooldown: 0,
    effect: '',
    passive: 'This item sells for $3',
    cost: 0,
    types: [],
    size: 'small',
  },
  {
    name: 'Regal Blade',
    image: 'regal-blade.png',
    cooldown: 9,
    effect: '2 Damage',
    passive: 'Whenever you sell an item, give this +2 permanently.',
    cost: 3,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Robe',
    image: 'robe.png',
    cooldown: 5,
    effect: 'Gain 5 Shield',
    passive: 'When you get this gain 10 Armor.',
    cost: 5,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Safe',
    image: 'safe.png',
    cooldown: 0,
    effect: '',
    passive:
      'At the start of the fight, permanently transform this into 2 random small items.',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Scrolls',
    image: 'placeholder.png',
    cooldown: 0,
    effect: '',
    passive: "Reduce your item's cooldowns by 21%.",
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Shisha',
    image: 'shisha.png',
    cooldown: 8,
    effect: 'Heal 5 Health',
    passive: 'When you Heal, Daze your opponent for 3 Seconds.',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Signet Ring',
    image: 'placeholder.png',
    cooldown: 9,
    effect: 'Gain Regeneration equal to your income.',
    passive: 'When you buy this, gain 2 income.',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'Silk',
    image: 'silk.png',
    cooldown: 0,
    effect: '',
    passive:
      'Sells for 0. When you sell this, fill your board with random items',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Sizeable Contract',
    image: 'sizeable-contract.png',
    cooldown: 8,
    effect: '18 Health',
    passive:
      'When you use a medium item, 1 Second Advance your Large and Small items.',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Skyscraper',
    image: 'skyscraper.png',
    cooldown: 8,
    effect: 'Deal Damage equal to your Shield.',
    passive: 'Whenever you use another item, gain 15 Shield.',
    cost: 12,
    types: ['Property', ' Weapon'],
    size: 'large',
  },
  {
    name: 'Slingshot',
    image: 'slingshot.png',
    cooldown: 9,
    effect: 'Deal 3 Damage for each small item you own.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Snow Globe',
    image: 'snow-globe.png',
    cooldown: 8,
    effect: '2 Seconds Freeze on two items of each player.',
    passive: '',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Snowtel',
    image: 'placeholder.png',
    cooldown: 4,
    effect: 'Freeze a random enemy item for 2 seconds.',
    passive: 'Whenever you Freeze, Heal for 20',
    cost: 11,
    types: ['Property'],
    size: 'medium',
  },
  {
    name: 'Spacescraper',
    image: 'spacescraper.png',
    cooldown: 6,
    effect: 'Gain 10 Shield',
    passive: 'When you gain money give this +2 Shield permanently.',
    cost: 12,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Spices',
    image: 'spices.png',
    cooldown: 12,
    effect: 'Double your Strength for this fight',
    passive: '',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'Spiky Shield',
    image: 'placeholder.png',
    cooldown: 8,
    effect: 'Deal damage equal to your Shield.',
    passive: '',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Subscraper',
    image: 'subscraper.png',
    cooldown: 7,
    effect: 'Gain 30 Shield for each building you own.',
    passive: '',
    cost: 0,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Succulents',
    image: 'succulents.png',
    cooldown: 8,
    effect: 'Heal 4. \nGive this +4 Healing for the fight.',
    passive: '',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Tea Set',
    image: 'placeholder.png',
    cooldown: 0,
    effect: '',
    passive: 'At the start of each fight, permanently gain +20 Max Health.',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Textiles',
    image: 'textiles.png',
    cooldown: 5,
    effect: 'Gain 5 Shield',
    passive:
      'Whenever you use a weapon, give all your shielding items +2 Shield this fight.',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Truffles',
    image: 'truffles.png',
    cooldown: 0,
    effect: '',
    passive: 'Every 3 times you Heal, gain 1 Strength this fight.',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Vending Machine',
    image: 'vending-machine.png',
    cooldown: 7,
    effect: '1 Strength per 150 Max Health you have.',
    passive: 'At the start of a fight, gain a Chocolate Bar.',
    cost: 5,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Vineyard',
    image: 'vineyard.png',
    cooldown: 7,
    effect: 'Heal 4',
    passive: 'When you Heal, gain 1 Strength.',
    cost: 12,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Weights',
    image: 'weights.png',
    cooldown: 9,
    effect: 'Gain 3 Strength this fight',
    passive: '',
    cost: 12,
    types: [],
    size: 'medium',
  },
  {
    name: 'Windmill',
    image: 'windmill.png',
    cooldown: 10,
    effect: 'Heal 20',
    passive: 'When you Heal, gain 3 Speed for this fight.',
    cost: 12,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Yo-Yo',
    image: 'yo-yo.png',
    cooldown: 4,
    effect: 'Deal 1 Damage',
    passive: '',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
]

export const dooleyCards: CardProps[] = [
  {
    name: 'Angry Balloon Bot',
    image: 'angry-balloon-bot.png',
    cooldown: 6,
    effect: '12 Damage',
    passive: '3 Strength',
    cost: 0,
    types: ['Friend', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Anne Plifier',
    image: 'anne-plifier.png',
    cooldown: 8,
    effect: '12 Health plus 12 more if you own another Friend.',
    passive: 'The left Friend charges 12% faster.',
    cost: 10,
    types: ['Friend'],
    size: 'medium',
  },
  {
    name: 'Avant Guard',
    image: 'avant-guard.png',
    cooldown: 8,
    effect: '3 Damage and 1 Seconds Daze per weapon your opponent owns.',
    passive: '',
    cost: 5,
    types: ['Friend', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Balloon Bot',
    image: 'balloon-bot.png',
    cooldown: 12,
    effect: '30 Shield',
    passive: '20 Armor\nWhen your Shield breaks, this gets Angry.',
    cost: 5,
    types: ['Friend'],
    size: 'medium',
  },
  {
    name: 'Beta Ray',
    image: 'beta-ray.png',
    cooldown: 10,
    effect: '5 Damage and 1 Freeze per Ray you own.',
    passive: '',
    cost: 4,
    types: ['Ray', ' Weapon'],
    size: 'small',
  },
  {
    name: 'Bomb Squad',
    image: 'bomb-squad.png',
    cooldown: 6,
    effect: '10 Damage',
    passive: 'This has Ammo equal to the Core level.',
    cost: 2,
    types: ['Friend', ' Weapon'],
    size: 'small',
  },
  {
    name: 'Capacitor',
    image: 'capacitor.png',
    cooldown: 7,
    effect: 'Advance the right item 2 seconds.',
    passive: '',
    cost: 4,
    types: ['Attachment'],
    size: 'small',
  },
  {
    name: 'Chris Army Knife',
    image: 'chris-army-knife.png',
    cooldown: 5,
    effect: 'Damage equal to your Core level.',
    passive: '',
    cost: 2,
    types: ['Friend', ' Weapon'],
    size: 'small',
  },
  {
    name: 'Claw',
    image: 'claw.png',
    cooldown: 9,
    effect: '15 Damage',
    passive: 'Gets +5 Damage when your Shield breaks (goes to 0).',
    cost: 5,
    types: ['Attachment', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Cool LEDs',
    image: 'cool-leds.png',
    cooldown: 6,
    effect: '2 Speed',
    passive: '1 Income',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Coolant',
    image: 'coolant.png',
    cooldown: 8,
    effect: '3 Seconds Freeze',
    passive: '',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: "Dooley's Bed",
    image: "dooley's-bed.png",
    cooldown: 8,
    effect: ' Add Strength equal to your Regeneration',
    passive: 'At the start of the day, +1 Regeneration permanently.',
    cost: 5,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Fiber Optics',
    image: 'fiber-optics.png',
    cooldown: 7,
    effect: '3 Speed',
    passive:
      'When you use the left most item, advance the right most item 1 second.',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'Forklift',
    image: 'forklift.png',
    cooldown: 10,
    effect: '15 Damage\n3 Strength',
    passive: '',
    cost: 4,
    types: ['Vehicle', ' Weapon'],
    size: 'large',
  },
  {
    name: 'Gamma Ray',
    image: 'gamma-ray.png',
    cooldown: 8,
    effect: '6 Damage',
    passive: 'When you use a Ray, 1 Poison.',
    cost: 8,
    types: ['Ray', ' Weapon'],
    size: 'small',
  },
  {
    name: 'Gearnola Bar',
    image: 'gearnola-bar.png',
    cooldown: 12,
    effect: '50 Health',
    passive: 'Get +10 Max Health',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Kinetic Cannon',
    image: 'kinetic-cannon.png',
    cooldown: 14,
    effect: '50 Damage',
    passive: ' +5 Damage when an opponent uses an item.',
    cost: 12,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'King Tyrone',
    image: 'king-tyrone.png',
    cooldown: 13,
    effect: '40 Damage',
    passive: 'Dualcast\nPiercing',
    cost: 12,
    types: ['Friend', ' Weapon'],
    size: 'large',
  },
  {
    name: 'Komi, Anne & Doe',
    image: 'komi,-anne-&-doe.png',
    cooldown: 11,
    effect: '22 Damage',
    passive: 'Adjacent Friends charge 10% faster.',
    cost: 3,
    types: ['Friend', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Laser Pistol',
    image: 'laser-pistol.png',
    cooldown: 4,
    effect: '8 Damage',
    passive: '',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Micro Dave',
    image: 'micro-dave.png',
    cooldown: 7,
    effect: '4 Burn\n4 Strength',
    passive: '',
    cost: 5,
    types: ['Friend'],
    size: 'medium',
  },
  {
    name: 'Nuclear Reactor',
    image: 'nuclear-reactor.png',
    cooldown: 12,
    effect: 'Your items get +1 Ammo.\n\n8 Burn to BOTH players.',
    passive: '',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Pierre Conditioner ',
    image: 'pierre-conditioner-.png',
    cooldown: 8,
    effect: '2 Seconds Freeze',
    passive:
      'Each time this is used, increase the number of targets by 1, to a max of 5.',
    cost: 10,
    types: ['Friend'],
    size: 'medium',
  },
  {
    name: 'Plasma Rifle',
    image: 'plasma-rifle.png',
    cooldown: 6,
    effect: '12 Damage per Ammo this has.',
    passive: '',
    cost: 3,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Power Drill',
    image: 'power-drill.png',
    cooldown: 6,
    effect: "8 Damage and then this get's 8 Damage.",
    passive: '',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Power Sander',
    image: 'power-sander.png',
    cooldown: 7,
    effect: 'Your shielding items get +4 Shield.',
    passive: ' +3 Armor Permanently.',
    cost: 4,
    types: ['Tools'],
    size: 'small',
  },
  {
    name: 'Pylon',
    image: 'pylon.png',
    cooldown: 10,
    effect: '20 Shield',
    passive: '',
    cost: 4,
    types: [],
    size: 'large',
  },
  {
    name: 'Red Button',
    image: 'red-button.png',
    cooldown: 13,
    effect: 'Destroy another random non-Core item you own and 100 Damage.',
    passive: '',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'Remote Control',
    image: 'remote-control.png',
    cooldown: 8,
    effect: '2 Seconds Advance the core.',
    passive: 'When you use an Adjacent Friend, 1 Second Advance this.  ',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'Rocket Launcher',
    image: 'rocket-launcher.png',
    cooldown: 12,
    effect: '60 Damage\n8 Burn',
    passive: '',
    cost: 10,
    types: ['Attachment', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Security Camera',
    image: 'security-camera.png',
    cooldown: 6,
    effect:
      'Speed equal to 10% of your opponents Speed. Strength equal to 10% of your opponents Strength.',
    passive: '',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Tesla Coil',
    image: 'tesla-coil.png',
    cooldown: 8,
    effect: '8 Damage',
    passive: 'When you use an adjacent item, 8 Damage.',
    cost: 8,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'The Core',
    image: 'the-core.png',
    cooldown: 12,
    effect: '10 Damage \nAdvance all items to the right by 1 Second.',
    passive: 'When any item to the left is used, Advance this 1 Second.',
    cost: 0,
    types: ['Core', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Thrusters',
    image: 'thrusters.png',
    cooldown: 13,
    effect: '15 Shield',
    passive: '15 Speed',
    cost: 4,
    types: ['Attachment', ' Gear'],
    size: 'small',
  },
  {
    name: 'Titanium',
    image: 'titanium.png',
    cooldown: 0,
    effect: '',
    passive: '30 Armor\n\nThe Core gets +5 Damage',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Weakpoint Detector',
    image: 'weakpoint-detector.png',
    cooldown: 8,
    effect: '3 Damage per filled slot to the left.',
    passive: 'When you use The Core, 3 Burn.',
    cost: 5,
    types: ['Attachment', ' Weapon'],
    size: 'medium',
  },
]

export const julesCards: CardProps[] = [
  {
    name: 'Alien Burrito',
    image: 'alien-burrito.png',
    cooldown: 5,
    effect: '9 Joy',
    passive: '',
    cost: 3,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Alien Trail Mix',
    image: 'alien-trail-mix.png',
    cooldown: 10,
    effect: '5 Joy',
    passive: 'When you use an Ingredient, 1 Second Advance this.',
    cost: 4,
    types: ['Ingredient', ' Meal'],
    size: 'small',
  },
  {
    name: 'Apron',
    image: 'apron.png',
    cooldown: 8,
    effect: 'Gain 4 Shield',
    passive:
      'Whenever you use a Meal or Ingredient item, give this +4 Shield for the fight.',
    cost: 5,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Birthday Cake',
    image: 'placeholder.png',
    cooldown: 17,
    effect: 'Joy for 7 times the Day count',
    passive: '',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Blender',
    image: 'blender.png',
    cooldown: 12,
    effect: '20 Damage',
    passive:
      'When you use the left small item, Advance the small right item by 1 second.',
    cost: 4,
    types: ['Weapon', ' Appliance'],
    size: 'medium',
  },
  {
    name: 'Blueberry Pie',
    image: 'blueberry-pie.png',
    cooldown: 9,
    effect: '7 Joy',
    passive: 'If you have 3 or more food items, this deals double Joy.',
    cost: 3,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Bread',
    image: 'bread.png',
    cooldown: 7,
    effect: '4 Joy',
    passive: 'When you use a Weapon, give +4 Joy for this fight.',
    cost: 5,
    types: ['Meal', ' Ingredient'],
    size: 'medium',
  },
  {
    name: 'Bread Knife',
    image: 'bread-knife.png',
    cooldown: 8,
    effect: 'Deal 12 Damage and Advance 2 seconds to adjacent Meals.',
    passive: ' ',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Butter',
    image: 'butter.png',
    cooldown: 8,
    effect: 'Give your Meals +1 Joy.',
    passive: 'Your Meals charge 20% faster.',
    cost: 3,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Cake Batter',
    image: 'cake-batter.png',
    cooldown: 9,
    effect: '20 Joy',
    passive: 'When you use an adjacent Weapon, 4 Joy.',
    cost: 10,
    types: ['Meal', ' Ingedient'],
    size: 'medium',
  },
  {
    name: 'Carving Fork',
    image: 'carving-fork.png',
    cooldown: 5,
    effect: 'Deal 2 Damage',
    passive: 'Piercing, Dualcast',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Caviar',
    image: 'caviar.png',
    cooldown: 11,
    effect:
      'Apply Joy to your opponent equal to the total value of their board.',
    passive: '',
    cost: 8,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Cheese Wheel',
    image: 'placeholder.png',
    cooldown: 24,
    effect: '40 Joy and give this +5 Joy.',
    passive: 'When you opponent uses a Weapon this Advances 1.',
    cost: 5,
    types: ['Ingredient', ' Meal'],
    size: 'medium',
  },
  {
    name: 'Chocolate Coin',
    image: 'chocolate-coin.png',
    cooldown: 6,
    effect: '2 Joy',
    passive: 'If you have 5 or more gold, this gains 2 Value.',
    cost: 2,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Chopsticks',
    image: 'chopsticks.png',
    cooldown: 10,
    effect: 'Give the right Meal +4 Joy.',
    passive: 'Whenever you use an ingredient, Advance this by 1 second.',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Coffee',
    image: 'coffee.png',
    cooldown: 6,
    effect: '2 Joy',
    passive: 'You have 10 Speed while holding this.',
    cost: 2,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Cookies',
    image: 'cookies.png',
    cooldown: 4,
    effect: '18 Joy',
    passive: 'All food gives +1 Joy',
    cost: 0,
    types: ['Food'],
    size: 'small',
  },
  {
    name: 'Cooking Mallet',
    image: 'cooking-mallet.png',
    cooldown: 7,
    effect: 'Deal 11 Damage and 2 Seconds Daze.',
    passive: 'If you own an Ingredient, this deal double the Damage.',
    cost: 3,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Cornucopia',
    image: 'cornucopia.png',
    cooldown: 8,
    effect: '5 Joy',
    passive: 'When you deal Joy, give this 5 Joy for the fight.',
    cost: 10,
    types: ['Meal', ' Ingredient'],
    size: 'medium',
  },
  {
    name: 'Curry',
    image: 'curry.png',
    cooldown: 11,
    effect: '10 Joy and 4 Burn',
    passive: 'Charges 50% faster while enemy is burning.',
    cost: 4,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Decanter',
    image: 'decanter.png',
    cooldown: 9,
    effect: 'Heal both players 15.',
    passive: 'Healing effects on you Heal +5 more.',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Dishwasher',
    image: 'placeholder.png',
    cooldown: 20,
    effect: '30 Health',
    passive: 'When you deal Joy, Advance this by 1.',
    cost: 4,
    types: ['Appliance'],
    size: 'large',
  },
  {
    name: 'Dragonmelon',
    image: 'placeholder.png',
    cooldown: 19,
    effect: '100 Joy',
    passive: '',
    cost: 10,
    types: ['Meal', ' Ingredient'],
    size: 'medium',
  },
  {
    name: 'Durian',
    image: 'durian.png',
    cooldown: 11,
    effect: '15 Damage\n15 Joy',
    passive: '',
    cost: 5,
    types: ['Weapon', ' Meal', ' Ingredient'],
    size: 'medium',
  },
  {
    name: 'Egg Timer',
    image: 'egg-timer.png',
    cooldown: 7,
    effect: 'Advance adjacent small items by 1 Second.',
    passive: '',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Eggs',
    image: 'eggs.png',
    cooldown: 6,
    effect: 'Both players gain +1 Strength for the fight.',
    passive: 'Adjacent food has +1 Joy for each Strength the opponent has.',
    cost: 2,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Farmers Market',
    image: 'placeholder.png',
    cooldown: 11,
    effect: '50 Health',
    passive: 'When you gain an item, the left Meal gets +1 Joy permanently.',
    cost: 6,
    types: ['Appliance', ' Ingredient'],
    size: 'large',
  },
  {
    name: 'Feast',
    image: 'feast.png',
    cooldown: 7,
    effect: '30 Joy\n30 Health\n2 Strength',
    passive: '',
    cost: 12,
    types: ['Meal'],
    size: 'large',
  },
  {
    name: 'Food Cart',
    image: 'food-cart.png',
    cooldown: 8,
    effect: '50 Joy and 25 Shield',
    passive: '',
    cost: 6,
    types: ['Meal', ' Vehicle'],
    size: 'large',
  },
  {
    name: 'Foraged Mushrooms',
    image: 'foraged-mushrooms.png',
    cooldown: 7,
    effect: 'Heal 35 Health.',
    passive: 'When you use a Medium item, 5 Joy.',
    cost: 10,
    types: ['Meal', ' Ingredient'],
    size: 'medium',
  },
  {
    name: 'Fortune Cookies',
    image: 'placeholder.png',
    cooldown: 7,
    effect: '3 Joy',
    passive: 'When you sell this, gain an extra event choice for the day.',
    cost: 8,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Fruit Press',
    image: 'fruit-press.png',
    cooldown: 8,
    effect: '40 Health to both players.',
    passive: '',
    cost: 6,
    types: [],
    size: 'medium',
  },
  {
    name: 'Giant Lollypop',
    image: 'giant-lollypop.png',
    cooldown: 3,
    effect: '15 Joy. This gets -1 Joy for the fight.',
    passive: '',
    cost: 6,
    types: ['Meal'],
    size: 'large',
  },
  {
    name: 'Giant Sub',
    image: 'giant-sub.png',
    cooldown: 12,
    effect: '36 Joy',
    passive: 'This had +20 Joy for each item you own.',
    cost: 12,
    types: ['Meal'],
    size: 'large',
  },
  {
    name: 'Gingerbread House',
    image: 'gingerbread-house.png',
    cooldown: 11,
    effect: '100 Joy and increase this items cooldown by 4 Seconds.',
    passive: '',
    cost: 12,
    types: ['Meal'],
    size: 'large',
  },
  {
    name: 'Grater',
    image: 'grater.png',
    cooldown: 8,
    effect: 'Deal 4 Damage for each small item you own.',
    passive:
      'At the start of the fight transform the right large item into 3 small items for the fight.',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Grill',
    image: 'grill.png',
    cooldown: 9,
    effect: '10 Burn',
    passive: 'When you use the right-most item, 2 Burn.',
    cost: 12,
    types: ['Appliance'],
    size: 'large',
  },
  {
    name: 'Herb Shears',
    image: 'herb-shears.png',
    cooldown: 5,
    effect: 'This deals +4 Damage for each Ingredient you have.',
    passive: '',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Honeycomb',
    image: 'honeycomb.png',
    cooldown: 8,
    effect: 'Heal 8 Health.',
    passive: '',
    cost: 2,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Hot Potato',
    image: 'hot-potato.png',
    cooldown: 8,
    effect: '8 Burn and 1 Joy. This gets -1 Burn and +1 Joy.',
    passive: '',
    cost: 4,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Hotbox',
    image: 'hotbox.png',
    cooldown: 0,
    effect: '',
    passive:
      'When you use the left item, 4 burn. When you use the right item, 5 joy.',
    cost: 5,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Ice Cubes',
    image: 'ice-cubes.png',
    cooldown: 10,
    effect: '2 seconds Freeze',
    passive: 'When you use adjacent Food item, 2 Seconds Freeze.',
    cost: 4,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Ice Swan',
    image: 'ice-swan.png',
    cooldown: 0,
    effect: '',
    passive: 'When you use an adjacent Weapon, 2 Seconds Freeze.',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Instant Noodles',
    image: 'instant-noodles.png',
    cooldown: 6,
    effect: '30 Joy',
    passive: '',
    cost: 4,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Jambalaya',
    image: 'jambalaya.png',
    cooldown: 9,
    effect: '12 Joy',
    passive: 'When you use an Ingredient, give this +6 Joy for the fight.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Juice',
    image: 'juice.png',
    cooldown: 8,
    effect: 'Heal both players 10. 2 Joy.',
    passive: '',
    cost: 3,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Knife Set',
    image: 'knife-set.png',
    cooldown: 6,
    effect: 'Deal 20 Damage',
    passive:
      'When you use an Ingredient, this gains +2 Damage and Advance 3 seconds.',
    cost: 3,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: "Laurel's Favourite",
    image: 'placeholder.png',
    cooldown: 10,
    effect: '20 Joy',
    passive: 'When you get a Meal or Ingredient, give this +2 Joy permanently.',
    cost: 3,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: "Laurel's Fortress",
    image: 'placeholder.png',
    cooldown: 15,
    effect: '30 Shield',
    passive:
      'When you sell a Meal or Ingredient, give this +3 Shield permanently.',
    cost: 4,
    types: ['Appliance'],
    size: 'large',
  },
  {
    name: 'Meat Tenderizer',
    image: 'meat-tenderizer.png',
    cooldown: 10,
    effect: 'Deal 9 Damage',
    passive: 'Adjacent Meals charge 30% faster.',
    cost: 8,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Microwave',
    image: 'microwave.png',
    cooldown: 12,
    effect: 'Burn 2 for each item you own.',
    passive: 'Your meal items charge 25% faster but you have -2 Joy.',
    cost: 9,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Midday Snack',
    image: 'placeholder.png',
    cooldown: 6,
    effect: '1 Joy',
    passive: 'When you sell this, fully Heal.',
    cost: 2,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Mini Fridge',
    image: 'mini-fridge.png',
    cooldown: 8,
    effect: 'Freeze an enemy item for 1 for each small item you own.',
    passive:
      'Whenever your opponent uses a small item, 2 seconds freeze to it.',
    cost: 5,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Mouse Trap',
    image: 'mouse-trap.png',
    cooldown: 6,
    effect: 'Deal 15 Damage',
    passive:
      'When your opponent uses a Weapon, use this. When you use a meal, reload this.',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Oven',
    image: 'oven.png',
    cooldown: 7,
    effect: '3 Burn and Advance your Meals by 2 seconds.',
    passive: '',
    cost: 12,
    types: ['Appliance'],
    size: 'large',
  },
  {
    name: 'Oven Mitts',
    image: 'oven-mitts.png',
    cooldown: 6,
    effect: 'Remove 5 Burn from yourself.',
    passive: 'Your Burn items apply 1 extra.',
    cost: 3,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Pancakes',
    image: 'pancakes.png',
    cooldown: 5,
    effect: '23 Joy',
    passive: 'When you use this, increase the cooldown by 2 seconds.',
    cost: 11,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Pantry',
    image: 'pantry.png',
    cooldown: 11,
    effect: '2 Regeneration',
    passive: 'This gets +2 Regeneration for each Ingredient you own.',
    cost: 6,
    types: [],
    size: 'large',
  },
  {
    name: 'Pasta',
    image: 'pasta.png',
    cooldown: 7,
    effect: '20 Joy',
    passive: '',
    cost: 8,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Pasta Maker',
    image: 'pasta-maker.png',
    cooldown: 11,
    effect: 'Transform this into 2 Pasta for the fight.',
    passive: '',
    cost: 5,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Pizza',
    image: 'pizza.png',
    cooldown: 18,
    effect: '1 Joy',
    passive: 'Octocast',
    cost: 10,
    types: ['Meal'],
    size: 'large',
  },
  {
    name: 'Pizza Cutter',
    image: 'pizza-cutter.png',
    cooldown: 7,
    effect: ' Deal 10 Damage and advance the right meal by 3 seconds.',
    passive: '',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Purple Pumpkin',
    image: 'purple-pumpkin.png',
    cooldown: 10,
    effect: '10 Joy',
    passive: 'When you use an adjacent Meal item, give it 3 Joy for the fight.',
    cost: 10,
    types: ['Meal', ' Ingredient'],
    size: 'medium',
  },
  {
    name: 'Refrigerator',
    image: 'refrigerator.png',
    cooldown: 0,
    effect:
      'At the start of each fight, permanently give your Meal items +1 Joy.',
    passive: '',
    cost: 0,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Rice',
    image: 'placeholder.png',
    cooldown: 12,
    effect: '10 Joy',
    passive: 'When you use an Appliance, give this +5 Joy.',
    cost: 0,
    types: ['Ingredient', ' Meal'],
    size: 'medium',
  },
  {
    name: 'Rice Cooker',
    image: 'placeholder.png',
    cooldown: 7,
    effect: '',
    passive: 'Advance your other medium items by 2 Seconds.',
    cost: 5,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Rolling Pin',
    image: 'rolling-pin.png',
    cooldown: 9,
    effect: 'Deal 22 Damage and Advance the left item by 3 Seconds.',
    passive: '',
    cost: 5,
    types: ['Gear', ' Weapon'],
    size: 'medium',
  },
  {
    name: 'Saffron',
    image: 'placeholder.png',
    cooldown: 0,
    effect: '',
    passive: 'Adjacent Meals add Joy equal to one-third their value.',
    cost: 8,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Salt',
    image: 'salt.png',
    cooldown: 10,
    effect: 'Give adjacent meal items +3 Joy.',
    passive: 'Tricast',
    cost: 4,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Seafood Cracker',
    image: 'seafood-cracker.png',
    cooldown: 7,
    effect: 'Deal 5 Damage',
    passive: 'This deals triple damage to shielded opponents.',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Serving Platter',
    image: 'serving-platter.png',
    cooldown: 12,
    effect: '10 Joy and Heal both players by 40.',
    passive: 'When you use an adjacent Weapon, Advance this 1 Second.',
    cost: 4,
    types: [],
    size: 'medium',
  },
  {
    name: 'Skewer',
    image: 'skewer.png',
    cooldown: 7,
    effect:
      'Deal 9 Damage and apply 2 Joy for each Meal or Ingredient you own.',
    passive: '',
    cost: 8,
    types: ['Weapon', ' Meal'],
    size: 'small',
  },
  {
    name: 'Skillet',
    image: 'skillet.png',
    cooldown: 8,
    effect: 'This items passive gets +1 Burn for the fight.',
    passive: 'When you use an adjacent Ingredient or Meal item Burn 2.',
    cost: 5,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Slushee',
    image: 'slushee.png',
    cooldown: 10,
    effect: '20 Joy. 2 Seconds Freeze to 2 enemy items.',
    passive: '',
    cost: 4,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Sorbet',
    image: 'sorbet.png',
    cooldown: 13,
    effect: '15 Joy and 5 Seconds Freeze to a random enemy item.',
    passive: '',
    cost: 8,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Spatula',
    image: 'spatula.png',
    cooldown: 7,
    effect: '7 Damage',
    passive:
      ' +7 Speed if you own an Ingredient\n +7 Speed if you own a Meal\n +7 Speed if you own an Appliance',
    cost: 8,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Spice Rack',
    image: 'spice-rack.png',
    cooldown: 10,
    effect: 'Gain 15 Speed for the fight.',
    passive: 'When you buy an Ingredient, permanently give this +5 Speed. ',
    cost: 0,
    types: ['Ingredient'],
    size: 'medium',
  },
  {
    name: 'Spicy Pepper',
    image: 'spicy-pepper.png',
    cooldown: 9,
    effect: '6 Burn and 2 Daze',
    passive: '',
    cost: 5,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Stew',
    image: 'stew.png',
    cooldown: 12,
    effect: '18 Joy',
    passive: 'When you use a small item, Advance this by 1 Second.',
    cost: 5,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Strawberry',
    image: 'placeholder.png',
    cooldown: 4,
    effect: 'Heal both players 3',
    passive: "Adjacent Meals have +3 Joy or +10 Joy if they're large.",
    cost: 4,
    types: ['Meal', ' Ingredient'],
    size: 'small',
  },
  {
    name: 'Sushi Boat',
    image: 'sushi-boat.png',
    cooldown: 6,
    effect: '15 Health',
    passive: 'When you Heal, 10 Joy.',
    cost: 12,
    types: ['Meal', ' Vehicle'],
    size: 'large',
  },
  {
    name: 'Tea Siphon',
    image: 'tea-siphon.png',
    cooldown: 11,
    effect: '6 Burn and Heal 20',
    passive: '',
    cost: 10,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Toaster',
    image: 'toaster.png',
    cooldown: 7,
    effect: '3 Burn',
    passive: 'Adjacent small meals items have Dualcast.',
    cost: 10,
    types: ['Appliance'],
    size: 'medium',
  },
  {
    name: 'Ulu Knife',
    image: 'ulu-knife.png',
    cooldown: 7,
    effect:
      'Deal 14 Damage. Advance adjacent Meal or Ingredient items by 2 Seconds.',
    passive: '',
    cost: 8,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Universal Sauce',
    image: 'placeholder.png',
    cooldown: 15,
    effect: 'The left Meal gets +12 Joy.',
    passive: '',
    cost: 2,
    types: ['Ingredient'],
    size: 'small',
  },
  {
    name: 'Whisk',
    image: 'whisk.png',
    cooldown: 10,
    effect: '3 Damage',
    passive: 'After using this once, the cooldown becomes 2 Seconds.',
    cost: 0,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Zarlic Garlic',
    image: 'placeholder.png',
    cooldown: 0,
    effect: '',
    passive: 'Adjacent Meals have +7 Joy.',
    cost: 2,
    types: ['Ingredient'],
    size: 'small',
  },
]

export const stelleCards: CardProps[] = [
  {
    name: 'Airplane Glue',
    image: 'airplane-glue.png',
    cooldown: 5,
    effect:
      "If your opponent has Speed, they lose 5 Speed. If they don't, you gain 3 Altitude.",
    passive: '',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Altimeter',
    image: 'altimeter.png',
    cooldown: 4,
    effect: '2 Altitude',
    passive: 'When you take off, +5 Speed.',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'Anemometer',
    image: 'anemometer.png',
    cooldown: 7,
    effect: 'Shield equal to the total Speed of both players.',
    passive: '5 Speed \nAt the start of the fight, use this.',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Angle Grinder Drone',
    image: 'angle-grinder-drone.png',
    cooldown: 8,
    effect: '5 Damage per Tool you own.',
    passive: '',
    cost: 2,
    types: ['Drones', ' Tools', ' Vehicle', ' Weapon'],
    size: 'small',
  },
  {
    name: 'Atlas',
    image: 'atlas.png',
    cooldown: 0,
    effect: '',
    passive: 'You see an extra choice each round. \n\n+30 Max Health',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Aviators',
    image: 'aviators.png',
    cooldown: 10,
    effect: '3 Seconds Daze',
    passive: 'When either player recieves Daze, charge the left item 1 Second.',
    cost: 4,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Balloon Engine',
    image: 'balloon-engine.png',
    cooldown: 9,
    effect: 'Gain 5 Altitude, then Burn equal to your Altitude.',
    passive: '',
    cost: 9,
    types: ['Vehicle'],
    size: 'medium',
  },
  {
    name: 'Balloon Tower',
    image: 'balloon-tower.png',
    cooldown: 12,
    effect: '4 Altitude',
    passive: 'Take Off: 36 Damage',
    cost: 4,
    types: ['Property', ' Weapon'],
    size: 'large',
  },
  {
    name: 'Battle Drone ',
    image: 'battle-drone-.png',
    cooldown: 7,
    effect: '15 Damage',
    passive:
      'When you Take Off, if this items cooldown is greater than 3 Seconds, reduce it by 1 Second.',
    cost: 3,
    types: ['Weapon', ' Vehicle', ' Drone'],
    size: 'medium',
  },
  {
    name: 'Binoculars',
    image: 'binoculars.png',
    cooldown: 9,
    effect: 'Advance the right Tool or Gear by 2 Seconds.',
    passive: '',
    cost: 0,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Birdcage',
    image: 'birdcage.png',
    cooldown: 4,
    effect: 'Gain 2 Altitude and 2 Speed.',
    passive:
      'At the start of the day increase this items value by the number of items you own.',
    cost: 3,
    types: [],
    size: 'medium',
  },
  {
    name: 'Blow Torch',
    image: 'blow-torch.png',
    cooldown: 6,
    effect: '4 Burn',
    passive: '',
    cost: 2,
    types: ['Tools'],
    size: 'small',
  },
  {
    name: 'Bomb Voyage',
    image: 'bomb-voyage.png',
    cooldown: 10,
    effect: 'Deal Damage equal to three times your Altitude.',
    passive: 'When you use a Weapon +1 Altitude',
    cost: 0,
    types: ['Weapon', ' Vehicle'],
    size: 'medium',
  },
  {
    name: 'Buster',
    image: 'buster.png',
    cooldown: 10,
    effect: 'Destroy all of your opponents Shields, then 75 Damage.',
    passive: '',
    cost: 10,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Caracara',
    image: 'caracara.png',
    cooldown: 10,
    effect: 'Deal 20 Damage',
    passive:
      'When you crossover 10 Altitude, this gains 10 Damage for the fight.',
    cost: 9,
    types: ['Weapon', ' Vehicle'],
    size: 'medium',
  },
  {
    name: 'Clockwork Disc',
    image: 'clockwork-disc.png',
    cooldown: 12,
    effect: '10 Damage',
    passive: 'When you Take Off, your Weapons get +5 Damage.',
    cost: 0,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Daggerwing',
    image: 'daggerwing.png',
    cooldown: 15,
    effect: '15 Damage per Weapon you own.',
    passive:
      "When you reach 20 Altitude, use this and then it's base cooldown becomes 5.",
    cost: 6,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Darts',
    image: 'darts.png',
    cooldown: 10,
    effect: '3 Damage',
    passive: 'Tricast',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'De-Icing Cart',
    image: 'placeholder.png',
    cooldown: 6,
    effect: 'Costs 6 Altitude\n6 Burn\nUnfreeze a frozen item you own.',
    passive: '',
    cost: 5,
    types: ['Tools'],
    size: 'medium',
  },
  {
    name: 'Delivery Drone',
    image: 'delivery-drone.png',
    cooldown: 9,
    effect: '20 Health\nGive adjacent items +1 Ammo',
    passive: 'At the start of a fight, give 3 Armor permanently.',
    cost: 5,
    types: ['Vehicle', ' Drone'],
    size: 'medium',
  },
  {
    name: 'Detonator',
    image: 'detonator.png',
    cooldown: 11,
    effect: 'Damage equal to the total value of your opponents items.',
    passive: '',
    cost: 4,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Feather',
    image: 'feather.png',
    cooldown: 8,
    effect: '4 Altitude',
    passive: 'Take Off: 2 Regeneration',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'Fire Bomb',
    image: 'fire-bomb.png',
    cooldown: 20,
    effect: '25 Burn',
    passive: '',
    cost: 6,
    types: [],
    size: 'small',
  },
  {
    name: 'Flare Gun',
    image: 'flare-gun.png',
    cooldown: 6,
    effect: '3 Damage and 3 Burn',
    passive: 'When you buy this, gain +3 Speed',
    cost: 0,
    types: [],
    size: 'small',
  },
  {
    name: 'Flash Grenade',
    image: 'flash-grenade.png',
    cooldown: 5,
    effect: '12 Damage and 12 Seconds Daze',
    passive: '',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Globe',
    image: 'globe.png',
    cooldown: 8,
    effect: 'Costs 4 Altitude: 6 Speed',
    passive: 'When you land, 6 Shield.',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Goggles',
    image: 'goggles.png',
    cooldown: 5,
    effect: 'Gain 1 Altitude.',
    passive:
      'When you Take Off or Land, adjacent weapons get +2 Damage this fight.',
    cost: 2,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Hammer',
    image: 'hammer.png',
    cooldown: 9,
    effect: '10 Damage per Tool or Gear you own.',
    passive: 'When adjacent Tool or Gear items are used, gain 5 Shield.',
    cost: 4,
    types: ['Weapon', ' Tool'],
    size: 'small',
  },
  {
    name: 'Hang Glider',
    image: 'hang-glider.png',
    cooldown: 5,
    effect: 'Costs 2 Altitude\n8 Shield\n8 Health',
    passive: '',
    cost: 4,
    types: ['Vehicle'],
    size: 'large',
  },
  {
    name: 'Hangar',
    image: 'hangar.png',
    cooldown: 2,
    effect: 'Replace this with one or 2 vehicles for this fight',
    passive: ' +25 Armor while you own this.',
    cost: 5,
    types: ['Building'],
    size: 'large',
  },
  {
    name: 'Ice Bomb',
    image: 'placeholder.png',
    cooldown: 20,
    effect: '5 Seconds Freeze on five items.',
    passive: '',
    cost: 8,
    types: [],
    size: 'small',
  },
  {
    name: 'In-Flight Meal',
    image: 'in-flight-meal.png',
    cooldown: 9,
    effect: 'Heal 10 + Your number of Altitude',
    passive: '',
    cost: 0,
    types: ['Meal'],
    size: 'medium',
  },
  {
    name: 'Jetpack',
    image: 'placeholder.png',
    cooldown: 7,
    effect: '6 Altitude\n6 Shield',
    passive: '',
    cost: 0,
    types: ['Vehicle'],
    size: 'small',
  },
  {
    name: 'Kite',
    image: 'kite.png',
    cooldown: 7,
    effect: '4 Speed',
    passive: 'When you Take Off, gain 2 Speed. ',
    cost: 6,
    types: [],
    size: 'medium',
  },
  {
    name: 'Lava Cycle',
    image: 'placeholder.png',
    cooldown: 9,
    effect: '5 Burn',
    passive: '',
    cost: 5,
    types: ['Vehicle'],
    size: 'medium',
  },
  {
    name: 'Lightning Rod',
    image: 'lightning-rod.png',
    cooldown: 40,
    effect: 'Absorbs all Damage that would be dealt to you for 5 Seconds.',
    passive: 'At start of fight, charge this 37 Seconds.',
    cost: 12,
    types: [],
    size: 'large',
  },
  {
    name: 'Marshallin Lights',
    image: 'marshallin-lights.png',
    cooldown: 7,
    effect: 'Lose 2 Altitude',
    passive: 'When you drop to 0 Altitude, Heal 25.',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Multitool',
    image: 'multitool.png',
    cooldown: 10,
    effect: '18 Shield',
    passive: 'When you Land, increase this items shielding by 2.',
    cost: 4,
    types: ['Tools'],
    size: 'small',
  },
  {
    name: 'Observatory',
    image: 'observatory.png',
    cooldown: 9,
    effect:
      'Costs 4 Altitude\n1 Daze per large item opponent owns.\n1 Freeze per medium item opponent owns.\n1 Burn per small item opponent owns.\n\n',
    passive: '',
    cost: 6,
    types: ['Appliance'],
    size: 'large',
  },
  {
    name: 'Ornithopter',
    image: 'ornithopter.png',
    cooldown: 7,
    effect: '2 Altitude',
    passive: '10 Armor',
    cost: 2,
    types: ['Vehicle'],
    size: 'small',
  },
  {
    name: 'Oxygen Mask',
    image: 'oxygen-mask.png',
    cooldown: 13,
    effect: 'Heal 20 Health\n+20 Health for each Gear you own.',
    passive: '',
    cost: 5,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Paper Airplane',
    image: 'paper-airplane.png',
    cooldown: 7,
    effect: 'Lose 4 Altitude\n8 Health',
    passive: 'Land: 2 Strength',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: 'Parachute',
    image: 'parachute.png',
    cooldown: 7,
    effect: 'Lose 20 Altitude\n50 Shield',
    passive: 'Land: This gets +10 Shield.',
    cost: 10,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: "Pilot's Wings",
    image: "pilot's-wings.png",
    cooldown: 12,
    effect: '4 Altitude',
    passive: 'At the start of the fight, charge your Vehicles 1 second.',
    cost: 4,
    types: ['Gear'],
    size: 'small',
  },
  {
    name: 'Pinwheel',
    image: 'pinwheel.png',
    cooldown: 0,
    effect: 'Channel: 6 Health every 3 seconds.',
    passive:
      "This doesn't charge, but begins Channelling once you reach 10 Altitude.",
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Pogo Stick',
    image: 'pogo-stick.png',
    cooldown: 9,
    effect:
      'If you have 0 Altitude, gain 2 Altitude. Otherwise, lose 2 Altitude.',
    passive: '',
    cost: 6,
    types: [],
    size: 'medium',
  },
  {
    name: 'Propane Tank',
    image: 'propane-tank.png',
    cooldown: 9,
    effect: 'Advance your Vehicles by 4.',
    passive: 'When you use a Vehicle, Burn 4.',
    cost: 9,
    types: [],
    size: 'medium',
  },
  {
    name: 'Propeller',
    image: 'propeller.png',
    cooldown: 0,
    effect: '10 Speed, 10 Altitude',
    passive: '',
    cost: 0,
    types: ['Vehicle'],
    size: 'medium',
  },
  {
    name: 'Radar Dome',
    image: 'radar-dome.png',
    cooldown: 14,
    effect: 'Regeneration equal to your Altitude.',
    passive: 'At the start of the fight, 6 Altitude.',
    cost: 12,
    types: ['Appliance'],
    size: 'large',
  },
  {
    name: 'Red Lantern',
    image: 'red-lantern.png',
    cooldown: 6,
    effect:
      '1 Second Freeze all of your items to the left. Charge the right item 2 Seconds per item frozen this way.',
    passive: '',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Rivet Gun',
    image: 'rivet-gun.png',
    cooldown: 7,
    effect: '6 Damage',
    passive:
      'When the item on the right is used, Advance the item on the left by 1 Second.',
    cost: 1,
    types: ['Weapon', ' Tool'],
    size: 'small',
  },
  {
    name: 'Rocket Drone',
    image: 'placeholder.png',
    cooldown: 6,
    effect: '5 Altitude\n5 Damage',
    passive: '',
    cost: 4,
    types: ['Weapon', ' Vehicle', ' Drone'],
    size: 'small',
  },
  {
    name: 'Sandbags',
    image: 'sandbags.png',
    cooldown: 7,
    effect:
      'Gain 2 Altitude and then deal damage equal to twice your Altitude.',
    passive: '',
    cost: 3,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Sirens',
    image: 'sirens.png',
    cooldown: 7,
    effect: '3 Daze',
    passive: 'When you use a Vehicle, 2 Seconds Daze.',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Solar Charging Drone',
    image: 'placeholder.png',
    cooldown: 10,
    effect: 'Charge adjacent large items by 2 Seconds.',
    passive: 'Your weapons gain Damage equal to the day count.',
    cost: 4,
    types: ['Vehicle', ' Drone'],
    size: 'small',
  },
  {
    name: 'Space Laser',
    image: 'space-laser.png',
    cooldown: 50,
    effect: '600 DAMAGE',
    passive: 'When you gain Altitude, ADVANCE THIS 2 SECONDS',
    cost: 12,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Squirrel suit',
    image: 'squirrel-suit.png',
    cooldown: 9,
    effect:
      'Gain Speed equal to your Altitude for this fight, then lose 2 Altitude.',
    passive: 'At the start of the fight, gain 5 Altitude.',
    cost: 0,
    types: ['Vehicle', ' Gear'],
    size: 'medium',
  },
  {
    name: 'Steam Hose',
    image: 'steam-hose.png',
    cooldown: 11,
    effect: '6 Damage, 6 Daze, 6 Burn',
    passive: '',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Stellar Swallowtail',
    image: 'stellar-swallowtail.png',
    cooldown: 7,
    effect: '18 Damage + Your Altitude as Damage.',
    passive: 'When you use a vehicle, gain 2 Altitude.',
    cost: 8,
    types: ['Weapon', ' Vehicle'],
    size: 'large',
  },
  {
    name: 'Teathers',
    image: 'teathers.png',
    cooldown: 6,
    effect: 'Costs 4 Altitude.\n4 Strength',
    passive: '',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'The Gossamer',
    image: 'placeholder.png',
    cooldown: 10,
    effect: 'Shield equal to 10 times the day count.',
    passive: '',
    cost: 6,
    types: ['Vehicle'],
    size: 'large',
  },
  {
    name: 'Toolbox',
    image: 'toolbox.png',
    cooldown: 7,
    effect: '20 Shield',
    passive:
      'At the start of the day, your weapons gain +10 Damage permanently.',
    cost: 4,
    types: [],
    size: 'medium',
  },
  {
    name: 'Turret',
    image: 'turret.png',
    cooldown: 8,
    effect: '16 Damage',
    passive: 'When the opponent uses an item Advance this by 1.',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Vehicle Blueprints',
    image: 'vehicle-blueprints.png',
    cooldown: 0,
    effect: '',
    passive: 'When you sell this, get a random Vehicle.',
    cost: 6,
    types: [],
    size: 'medium',
  },
  {
    name: 'Vortex Cannon',
    image: 'placeholder.png',
    cooldown: 10,
    effect: '20 Damage',
    passive:
      'This has multicast equal to the number of items the opponent owns.',
    cost: 12,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Weather Machine',
    image: 'weather-machine.png',
    cooldown: 14,
    effect:
      '50 Damage\n6 Burn \n2 Seconds Freeze ALL small items (This Freeze affects both players)',
    passive: '',
    cost: 12,
    types: ['Weapon', ' Vehicle'],
    size: 'large',
  },
  {
    name: 'Windbraker',
    image: 'windbraker.png',
    cooldown: 8,
    effect: 'Lose 8 Altitude ',
    passive: 'When you land +35 Shield.',
    cost: 4,
    types: [],
    size: 'medium',
  },
  {
    name: 'Wrecking Ball',
    image: 'wrecking-ball.png',
    cooldown: 15,
    effect: '55 Damage\n15 Second Daze',
    passive: '',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Wrench',
    image: 'wrench.png',
    cooldown: 12,
    effect: '20 Damage',
    passive: ' +20 Damage per Vehicle you own.',
    cost: 8,
    types: ['Weapon', ' Tool'],
    size: 'small',
  },
]

export const vanessaCards: CardProps[] = [
  {
    name: 'Anchor ',
    image: 'anchor.png',
    cooldown: 10,
    effect: '2 Daze for each Aquatic item you own.',
    passive: '',
    cost: 1,
    types: ['Aquatic'],
    size: 'medium',
  },
  {
    name: 'Arbalest',
    image: 'arbalest.png',
    cooldown: 9,
    effect: '8 Damage',
    passive:
      'When you use another item, give the Arbalest +2 Damage for the fight.',
    cost: 2,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Astrolabe ',
    image: 'astrolabe.png',
    cooldown: 1,
    effect: 'Do nothing',
    passive: '',
    cost: 3,
    types: [],
    size: 'medium',
  },
  {
    name: 'Ballista ',
    image: 'ballista.png',
    cooldown: 10,
    effect: '100 damage',
    passive: '   ',
    cost: 2,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Barrel ',
    image: 'barrel.png',
    cooldown: 9,
    effect: '9 Shield',
    passive: 'When you use another item, give this +1 Shield for the fight.',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: 'Beachball',
    image: 'beachball.png',
    cooldown: 7,
    effect: 'Advance the right-most or left-most item by 3 seconds.',
    passive: 'This alternates targets between uses.',
    cost: 6,
    types: [],
    size: 'medium',
  },
  {
    name: 'Blowgun ',
    image: 'blowgun.png',
    cooldown: 11,
    effect: '1 Damage and apply that much Poison.',
    passive: '',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Blunderbuss',
    image: 'blunderbuss.png',
    cooldown: 15,
    effect: '29 Damage',
    passive: 'When you Burn your opponent, use this.',
    cost: 0,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Bolas ',
    image: 'bolas.png',
    cooldown: 8,
    effect: '6 Damage\nDaze your opponent for 6 seconds.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Butterfly Swords',
    image: 'butterfly-swords.png',
    cooldown: 5,
    effect: '4 Damage',
    passive: 'Tricast',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Cannon ',
    image: 'cannon.png',
    cooldown: 5,
    effect: 'Deal 8 Damage and 4 Burn',
    passive: 'This has +1 Ammo for each weapon you own.',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Cannonade ',
    image: 'cannonade.png',
    cooldown: 16,
    effect: '40 Damage\n2 Burn',
    passive: 'Multicast per Weapon you own.',
    cost: 12,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Cannonball ',
    image: 'cannonball.png',
    cooldown: 0,
    effect: '',
    passive: 'When you use an item with Ammo, deal 5 Damage.',
    cost: 2,
    types: [],
    size: 'small',
  },
  {
    name: "Captain's Wheel  ",
    image: "captain's-wheel.png",
    cooldown: 0,
    effect: '',
    passive:
      'When any of the items to the left of this is used, 1 second Freeze. When any of the items used to the right of this is used, 4 Health.',
    cost: 5,
    types: [],
    size: 'medium',
  },
  {
    name: 'Chum ',
    image: 'chum.png',
    cooldown: 6,
    effect: 'Give Aquatic items +2 Damage.',
    passive: 'When you use an Aquatic item, gain +2 Speed.',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Citrus ',
    image: 'citrus.png',
    cooldown: 8,
    effect: '2 Strength and 2 Regeneration.',
    passive: '',
    cost: 4,
    types: [],
    size: 'small',
  },
  {
    name: 'Clamera ',
    image: 'clamera.png',
    cooldown: 12,
    effect: 'Daze your opponent for 4 seconds.',
    passive: 'At the start of each fight, use this',
    cost: 2,
    types: ['Aquatic'],
    size: 'small',
  },
  {
    name: 'Coconut ',
    image: 'coconut.png',
    cooldown: 4,
    effect: '1 Regeneration',
    passive: '',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Concealed Dagger',
    image: 'concealed-dagger.png',
    cooldown: 5,
    effect: 'Deal 4 Damage',
    passive:
      'This deals double Damage if you own less than 3 Weapons (counting this one).',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Coral ',
    image: 'coral.png',
    cooldown: 3,
    effect: 'Heal 4',
    passive: 'When you apply Poison, give this +8 Healing for the fight.',
    cost: 2,
    types: ['Aquatic'],
    size: 'small',
  },
  {
    name: 'Coral Armor ',
    image: 'coral-armor.png',
    cooldown: 7,
    effect: 'Gain 4 Shield for each weapon you own.',
    passive: '',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: "Crow's Nest ",
    image: "crow's-nest.png",
    cooldown: 7,
    effect: 'Give adjacent weapons +10% damage.',
    passive: 'You have 5 Speed for each Ammo item you own.',
    cost: 6,
    types: [],
    size: 'large',
  },
  {
    name: 'Cutlass ',
    image: 'cutlass.png',
    cooldown: 3,
    effect: 'Deal 4 damage',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Dam ',
    image: 'dam.png',
    cooldown: 11,
    effect: '40 damage',
    passive:
      'At the start of a fight permanently give this item +35 Damage for each Aquatic item you own.',
    cost: 3,
    types: ['Weapon\nAquatic'],
    size: 'large',
  },
  {
    name: 'Disguise',
    image: 'disguise.png',
    cooldown: 7,
    effect: 'Remove 10 shield from the enemy, you gain 10 shield.',
    passive: 'Adjacent non-ammo Weapons deal +5 Damage.',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Dock Lines',
    image: 'dock-lines.png',
    cooldown: 6,
    effect: 'Daze your opponent for 2 Seconds.',
    passive: '',
    cost: 1,
    types: [],
    size: 'medium',
  },
  {
    name: 'Double Barrel ',
    image: 'double-barrel.png',
    cooldown: 5,
    effect: 'Deal 3 Damage.',
    passive: 'Dualcast',
    cost: 0,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: "Dragon's Lair ",
    image: "dragon's-lair.png",
    cooldown: 3,
    effect: 'Transform this into 3 Small Weapons permanently.',
    passive: 'When you get this, Fight the Dragon.',
    cost: 12,
    types: ['Property'],
    size: 'large',
  },
  {
    name: 'Figurehead',
    image: 'figurehead.png',
    cooldown: 3,
    effect: '',
    passive:
      'You have +4 Strength, when you sell this give your Weapons +2 Damage.',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Fishing Net ',
    image: 'fishing-net.png',
    cooldown: 10,
    effect: 'Get a Piranha.',
    passive: ' You have +1 strength for each Aquatic item you own.',
    cost: 4,
    types: [],
    size: 'medium',
  },
  {
    name: 'Fishing Rod',
    image: 'fishing-rod.png',
    cooldown: 8,
    effect: 'Deal 2 damage and 3 Seconds Daze.',
    passive: 'At the start of fight get 1 random Aquatic item.',
    cost: 3,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Grappling Hook ',
    image: 'grappling-hook.png',
    cooldown: 10,
    effect: 'Daze 3 Seconds',
    passive: 'When you Daze you deal 31 Damage.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Grenade ',
    image: 'grenade.png',
    cooldown: 4,
    effect: '25 Damage.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Harpoon',
    image: 'harpoon.png',
    cooldown: 8,
    effect: '3 Damage\nGive this +3 Damage for the fight.',
    passive: '',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Holsters ',
    image: 'holsters.png',
    cooldown: 0,
    effect: '',
    passive: 'At the start of the fight, use adjacent small items.',
    cost: 0,
    types: [],
    size: 'small',
  },
  {
    name: 'Honing Steel',
    image: 'honing-steel.png',
    cooldown: 6,
    effect: 'Buff the left Weapon +2 Damage.',
    passive: '',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Iceberg ',
    image: 'iceberg.png',
    cooldown: 0,
    effect: '',
    passive:
      'When your opponent uses an item Freeze it for 1 Second, if its a Weapon Freeze it for 2 Seconds.',
    cost: 2,
    types: [],
    size: 'large',
  },
  {
    name: 'Incendiary Rounds ',
    image: 'incendiary-rounds.png',
    cooldown: 0,
    effect: '',
    passive:
      'At the start of fight give adjacent items +1 Ammo, when you use an Ammo Weapon Burn 2.',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Javelin ',
    image: 'javelin.png',
    cooldown: 13,
    effect: '5 Damage',
    passive: 'When any of the items to the right is used, this gets +1 Damage.',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Jellyfish',
    image: 'jellyfish.png',
    cooldown: 10,
    effect: '1 Poison',
    passive: 'When you Daze your opponent, use this.',
    cost: 2,
    types: ['Weapon\nAquatic'],
    size: 'small',
  },
  {
    name: 'Jitte ',
    image: 'jitte.png',
    cooldown: 10,
    effect: "6 Damage\nGive your opponent's Weapons -2 Damage this fight.",
    passive: '',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Life Presever ',
    image: 'life-presever.png',
    cooldown: 28,
    effect: '75 Health\n2 Regeneration',
    passive: 'When you use an Aquatic item, Charge 1 second to this.',
    cost: 10,
    types: ['Aquatic'],
    size: 'medium',
  },
  {
    name: 'Lighter',
    image: 'lighter.png',
    cooldown: 9,
    effect: '4 Burn',
    passive: 'If your opponent is Burning, this charges 50% faster',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Lighthouse ',
    image: 'lighthouse.png',
    cooldown: 0,
    effect: '',
    passive:
      '100 Armor\nAt the start of each fight Daze both players for 20 seconds',
    cost: 3,
    types: [],
    size: 'large',
  },
  {
    name: 'Matryoshka ',
    image: 'matryoshka.png',
    cooldown: 3,
    effect: "This deals damage equal to it's ammo times 2.",
    passive: '',
    cost: 8,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Musket ',
    image: 'musket.png',
    cooldown: 10,
    effect: '30 damage',
    passive: 'At the start of the fight, use this.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Octopus ',
    image: 'octopus.png',
    cooldown: 20,
    effect: '1 Damage',
    passive: 'Octocast',
    cost: 8,
    types: ['Weapon\nAquatic'],
    size: 'medium',
  },
  {
    name: 'Pearl ',
    image: 'pearl.png',
    cooldown: 0,
    effect: '',
    passive: 'The left item has dualcast.',
    cost: 3,
    types: ['Aquatic'],
    size: 'small',
  },
  {
    name: 'Pet Rock',
    image: 'pet-rock.png',
    cooldown: 8,
    effect: 'Deal 0 Damage and 1 Second Daze.',
    passive: 'At the start of each fight, this gets +1 Damage permanently.',
    cost: 2,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Pistol Sword ',
    image: 'pistol-sword.png',
    cooldown: 8,
    effect: 'Deal 10 Damage.',
    passive: 'When you Freeze an enemy item, advance 3 to this.',
    cost: 6,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Port ',
    image: 'port.png',
    cooldown: 7,
    effect: 'Give all your items +1 Ammo.',
    passive: 'Whenever you sell an item, give your Ammo Weapons +3 Damage.',
    cost: 3,
    types: [],
    size: 'large',
  },
  {
    name: 'Powder Flask ',
    image: 'powder-flask.png',
    cooldown: 8,
    effect: 'Give the item to the left of this +1 Ammo.',
    passive: '',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Powder Keg ',
    image: 'powder-keg.png',
    cooldown: 14,
    effect: "5 Burn, then double your opponent's Burn.",
    passive: '',
    cost: 2,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Pufferfish',
    image: 'pufferfish.png',
    cooldown: 12,
    effect: 'Apply 1 Poison',
    passive:
      'The first time you use this, its cooldown becomes 3 Seconds for the fight.',
    cost: 6,
    types: ['Weapon\nAquatic'],
    size: 'medium',
  },
  {
    name: 'Ramrod',
    image: 'ramrod.png',
    cooldown: 8,
    effect: 'Give the item to the right of this +2 Ammo.',
    passive: '',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Revolver ',
    image: 'revolver.png',
    cooldown: 6,
    effect: '28 Damage',
    passive: 'When you use another Weapon, use this.',
    cost: 3,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Rifle',
    image: 'rifle.png',
    cooldown: 5,
    effect: '12 Damage',
    passive:
      'At the start of each fight, this gains +1 Ammo for each Weapon you own.',
    cost: 1,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Sea Shell ',
    image: 'sea-shell.png',
    cooldown: 9,
    effect: 'Gain 5 shield for each Aquatic item you own.',
    passive: '',
    cost: 0,
    types: ['Aquatic'],
    size: 'small',
  },
  {
    name: 'Seaweed ',
    image: 'seaweed.png',
    cooldown: 4,
    effect: '3 Health',
    passive: 'Your Aquatic items charge 30% faster.',
    cost: 0,
    types: ['Aquatic'],
    size: 'small',
  },
  {
    name: 'Sextant ',
    image: 'sextant.png',
    cooldown: 0,
    effect: '',
    passive: 'When you use an item get 2 Speed for the fight.',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Sharkclaws',
    image: 'sharkclaws.png',
    cooldown: 5,
    effect: '4 Damage\n1 Strength',
    passive: '',
    cost: 10,
    types: ['Weapon', ' Aquatic'],
    size: 'medium',
  },
  {
    name: 'Sharkray',
    image: 'sharkray.png',
    cooldown: 10,
    effect: 'Deal 8 Damage and 1 Poison.',
    passive: 'Whenever you Posion your opponent, this Advances 2 seconds.',
    cost: 8,
    types: ['Weapon', ' Aquatic'],
    size: 'medium',
  },
  {
    name: 'Shipwreck ',
    image: 'shipwreck.png',
    cooldown: 15,
    effect:
      'Deal 80 Damage to the opponents and 20 Damage to yourself. Adjacent items become permanently Aquatic.',
    passive:
      'Reduce this items cooldown by 1 second for each Aquatic item you own.',
    cost: 0,
    types: ['Weapon', ' Aquatic', ' Vehicle'],
    size: 'large',
  },
  {
    name: 'Signal Fish',
    image: 'signal-fish.png',
    cooldown: 10,
    effect: 'Deal 20 Damage and 2 Seconds Freeze.',
    passive: '50% Lifesteal',
    cost: 8,
    types: ['Weapon', ' Aquatic'],
    size: 'small',
  },
  {
    name: 'Silencer',
    image: 'silencer.png',
    cooldown: 0,
    effect: '',
    passive:
      'The Weapon to the left of this deals +3 Damage. It charges 50% faster if you only own 1 Weapon.',
    cost: 1,
    types: [],
    size: 'small',
  },
  {
    name: 'Sniper Rifle ',
    image: 'sniper-rifle.png',
    cooldown: 0,
    effect: '50 damage',
    passive: 'Double this items Damage for each large item you own.',
    cost: 9,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Spyglass',
    image: 'spyglass.png',
    cooldown: 0,
    effect: 'Medium items charge 75% faster.',
    passive: '',
    cost: 0,
    types: [],
    size: 'medium',
  },
  {
    name: 'Star Chart ',
    image: 'star-chart.png',
    cooldown: 20,
    effect: 'Get 100 speed',
    passive: 'Adjacent items charge 40% faster.',
    cost: 10,
    types: [],
    size: 'medium',
  },
  {
    name: 'Stash',
    image: 'stash.png',
    cooldown: 0,
    effect: '',
    passive: 'At start of fight give your items +2 Ammo.',
    cost: 3,
    types: [],
    size: 'medium',
  },
  {
    name: 'Submarine ',
    image: 'submarine.png',
    cooldown: 0,
    effect: '10 Damage and gain that much as Shield.',
    passive: '',
    cost: 3,
    types: ['Weapon', '\nAquatic', ' Vehicle'],
    size: 'large',
  },
  {
    name: 'Swash Buckle ',
    image: 'swash-buckle.png',
    cooldown: 8,
    effect:
      'Gain 5 Speed and give adjacent non-ammo Weapons +2 Damage for the fight.',
    passive: 'When you buy this, gain 20 Armor permanently.',
    cost: 0,
    types: ['Gear'],
    size: 'medium',
  },
  {
    name: 'Switchblade ',
    image: 'switchblade.png',
    cooldown: 5,
    effect: 'Deal 3 damage.',
    passive: 'Deals triple Damage if all your Weapons are small.',
    cost: 3,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'The Boulder',
    image: 'the-boulder.png',
    cooldown: 30,
    effect: "Deal damage EQUAL TO YOUR OPPONENT'S MAX HEALTH.",
    passive: '',
    cost: 2,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Throwing Knives',
    image: 'throwing-knives.png',
    cooldown: 4,
    effect: '4 Damage',
    passive: 'When you use another Weapon, use this.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Trebuchet ',
    image: 'trebuchet.png',
    cooldown: 13,
    effect: '40 damage\n12 burn',
    passive: '',
    cost: 0,
    types: ['Weapon'],
    size: 'large',
  },
  {
    name: 'Tripwire ',
    image: 'tripwire.png',
    cooldown: 6,
    effect: '20 Damage, 3 Seconds Daze and 1 Poison.',
    passive: 'The first time an opponent uses an item, gain 30 Shield.',
    cost: 0,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Tropical Island ',
    image: 'tropical-island.png',
    cooldown: 0,
    effect: '',
    passive:
      'At the start of each fight, permanently gain 10 Max Health for each non-weapon item you own.',
    cost: 3,
    types: [],
    size: 'large',
  },
  {
    name: 'Trusty Handgun',
    image: 'trusty-handgun.png',
    cooldown: 4,
    effect: 'Deal 12 Damage',
    passive: 'When you use an adjacent Aquatic item, reload this.',
    cost: 5,
    types: ['Weapon'],
    size: 'medium',
  },
  {
    name: 'Turtle Shell ',
    image: 'turtle-shell.png',
    cooldown: 0,
    effect: '',
    passive: 'When you use an item, gain 4 Shield.',
    cost: 2,
    types: ['Aquatic'],
    size: 'medium',
  },
  {
    name: "Vanessa's Amulet ",
    image: 'placeholder.png',
    cooldown: 0,
    effect: '',
    passive:
      'When you use an adjacent Weapon, give it +3 Damage for the fight.',
    cost: 3,
    types: [],
    size: 'small',
  },
  {
    name: "Vanessa's Ship ",
    image: 'placeholder.png',
    cooldown: 5,
    effect: 'Deal Damage equal to the total value of your board.',
    passive: 'You have +3 Strength and +10 Speed.',
    cost: 0,
    types: ['Weapon', ' Vehicle'],
    size: 'large',
  },
  {
    name: 'Wanted Poster ',
    image: 'wanted-poster.png',
    cooldown: 0,
    effect: '',
    passive: "When you buy a Weapon, increase poster's value by $2.",
    cost: 3,
    types: [],
    size: 'medium',
  },
  {
    name: 'Waterwheel ',
    image: 'waterwheel.png',
    cooldown: 0,
    effect: 'Advance the right item by 10 Seconds.',
    passive: 'When you use the left item, Advance this 2 seconds. ',
    cost: 0,
    types: [],
    size: 'large',
  },
  {
    name: 'Weather Glass',
    image: 'weather-glass.png',
    cooldown: 0,
    effect: '',
    passive: 'Your items that apply status effects add +2 extra.',
    cost: 2,
    types: [],
    size: 'medium',
  },
]
