import type { CardProps } from '../components/card/Card'

export const cards: CardProps[] = [
  {
    name: 'Alien Axe',
    image: 'alien-axe.png',
    cooldown: 10,
    effect: '11 Damage',
    passive: 'When you get this, gain 2 speed permanently.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Bluenanas',
    image: 'bluenanas.png',
    cooldown: 10,
    effect: '15 Health',
    passive: 'When you get this, +10 Max Health.',
    cost: 1,
    types: ['Meal'],
    size: 'small',
  },
  {
    name: 'Alien Axe',
    image: 'alien-axe.png',
    cooldown: 10,
    effect: '11 Damage',
    passive: 'When you get this, gain 2 speed permanently.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Alien Axe',
    image: 'alien-axe.png',
    cooldown: 10,
    effect: '11 Damage',
    passive: 'When you get this, gain 2 speed permanently.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Alien Axe',
    image: 'alien-axe.png',
    cooldown: 10,
    effect: '11 Damage',
    passive: 'When you get this, gain 2 speed permanently.',
    cost: 1,
    types: ['Weapon'],
    size: 'small',
  },
  {
    name: 'Bluenanas',
    image: 'bluenanas.png',
    cooldown: 10,
    effect: '15 Health',
    passive: 'When you get this, +10 Max Health.',
    cost: 1,
    types: ['Meal'],
    size: 'small',
  },
]
